name: Check generated go files

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install protoc
        run: make install-protoc
  
      - name: Check gRPC generated files not manually changed
        shell: bash
        run: make check-grpc-files

      - name: Check sources
        run: make run-test
      - name: Build sources
        run: make build