name: Check generated go files

on: push

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler && protoc --version

      - name: Check gRPC generated files not manually changed
        shell: bash
        run: |
          make generate-grpc-files
          if ! git diff --name-only --exit-code ./*.go; then
            echo "Committed Protobuf files do not match the newly generated. Please, regenerate Protobuf and commit changes"
            exit 1
          fi

      - name: Check sources
        run: make run-test
      - name: Build sources
        run: make build