name: Update gRPC source

on:
  workflow_dispatch:
    inputs:
      grpc-common-tag:
        type: string
        default: ''
        description: "tag name of th2-grpc-common repository"
      grpc-lw-data-provider-tag:
        type: string
        default: ''
        description: "tag name of th2-lw-data-provider repository"

env:
  MAKEFILE: Makefile
  COMMON_VERSION_VARIABLE: TH2_GRPC_COMMON_VERSION
  LW_DATA_PROVIDER_VERSION_VARIABLE: LW_DATA_PROVIDER_VERSION_VARIABLE

jobs:
  update-grpc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check incoming variables
        id: variables
        shell: bash
        run: |
          if [[ -z "${{ inputs.grpc-common-tag }}" && -z "${{ inputs.grpc-lw-data-provider-tag }}" ]]; then
            echo "Both input variables are empty"
            exit 1
          fi

          comment=''
          if [[ -n "${{ inputs.grpc-common-tag }}" ]]; then
            echo "common-tag-valid=true" >> $GITHUB_OUTPUT
            comment="${comment} th2-grpc-common:${{ inputs.grpc-common-tag }}"
          else
            echo "common-tag-valid=false" >> $GITHUB_OUTPUT
          fi

          if [[ -n "${{ inputs.grpc-lw-data-provider-tag }}" ]]; then
            echo "lwdp-tag-valid=true" >> $GITHUB_OUTPUT
            comment="${comment} th2-lw-data-provider:${{ inputs.grpc-lw-data-provider-tag }}"
          else
            echo "lwdp-tag-valid=false" >> $GITHUB_OUTPUT
          fi
          echo "comment=${comment}" >> $GITHUB_OUTPUT
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          fetch-tags: true
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Install protoc
        run: make install-protoc
      - name: Update th2-grpc-common tag in Makefile
        shell: bash
        if: ${{ steps.variables.outputs.common-tag-valid == 'true' }} 
        run: |
          sed --in-place "s/^${{ env.COMMON_VERSION_VARIABLE }}=.*/${{ env.COMMON_VERSION_VARIABLE }}=${{ inputs.grpc-common-tag }} # Updated by Github workflow/" "${{ env.MAKEFILE }}"
      - name: Update th2-lw-data-provider tag in Makefile
        shell: bash
        if: ${{ steps.variables.outputs.lwdp-tag-valid  == 'true' }}
        run: |
          sed --in-place "s/^${{ env.LW_DATA_PROVIDER_VERSION_VARIABLE }}=.*/${{ env.LW_DATA_PROVIDER_VERSION_VARIABLE }}=${{ inputs.grpc-lw-data-provider-tag }} # Updated by Github workflow/" "${{ env.MAKEFILE }}"
      - name: Generate gRPC files
        shell: bash
        run: make generate-grpc-files
      - name: Check sources
        run: make run-test
      - name: Build sources
        run: make build
      - name: Update go.mod and go.sum
        run: make tidy
      - name: Commit changes and create tag
        uses: EndBug/add-and-commit@v9
        with:
          add: "['*.go', '${{ env.MAKEFILE }}']"
          default_author: github_actions
          message: "Updated gRPC source using${{ steps.variables.outputs.comment }}"
          tag: ${{ inputs.grpc-lw-data-provider-tag }}
      - name: Build changelog
        id: build_changelog
        if: ${{ steps.variables.outputs.lwdp-tag-valid == 'true' }}
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "COMMIT"
          configuration: .github/workflows/update-grpc-changelog-config.json
          toTag: ${{ inputs.grpc-lw-data-provider-tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        id: create_release
        if: ${{ steps.variables.outputs.lwdp-tag-valid == 'true' }}
        uses: ncipollo/release-action@v1.20.0
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
          name: Release ${{ inputs.grpc-common-tag }}, ${{ inputs.grpc-lw-data-provider-tag }}
          tag: ${{ inputs.grpc-lw-data-provider-tag }}
          token: ${{ secrets.GITHUB_TOKEN }}